- name: variables from PLAY level
  hosts: localhost
  vars_files:
  - variables.yaml
  tasks:
  - name: variables
    ansible.builtin.debug:
      msg: "I am learning {{Course}}, Trainer is {{Trainer}} , Duration is {{Duration}}"