- name: loops
  hosts: localhost
  tasks:
  - name: install or unistall packages
    ansible.builtin.debug:
      name: "{{item.name}}"
      state: "{{item.state}}"
    loop:
    - {name: 'git', state: 'present'} 
    - {name: 'mysql', state: 'absent'} 
