- name: install and run the nginx server
  hosts: localhost
  become: yes
  tasks:
  - name: install the niginx
    ansible.builtin.dnf:
      name: nginx
      state: present
  - name: run the nginx
    ansible.builtin.service:
      name: nginx
      state: started
